In [9]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
##vocabulary size
voc_size = 500

In [18]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[265, 112, 86, 7], [265, 112, 86, 60], [265, 468, 86, 188], [125, 408, 241, 277, 473], [125, 408, 241, 277, 357], [62, 265, 336, 86, 444], [363, 472, 154, 277]]


In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [20]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 265 112  86   7]
 [  0   0   0   0 265 112  86  60]
 [  0   0   0   0 265 468  86 188]
 [  0   0   0 125 408 241 277 473]
 [  0   0   0 125 408 241 277 357]
 [  0   0   0  62 265 336  86 444]
 [  0   0   0   0 363 472 154 277]]


In [21]:
dim = 10

In [23]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
embedded_docs[0]

array([  0,   0,   0,   0, 265, 112,  86,   7], dtype=int32)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[-0.02009135,  0.02014704,  0.0042727 , -0.02297195,
         -0.01993846,  0.03533003,  0.00348381, -0.04113201,
          0.04179699,  0.00231497],
        [-0.02009135,  0.02014704,  0.0042727 , -0.02297195,
         -0.01993846,  0.03533003,  0.00348381, -0.04113201,
          0.04179699,  0.00231497],
        [-0.02009135,  0.02014704,  0.0042727 , -0.02297195,
         -0.01993846,  0.03533003,  0.00348381, -0.04113201,
          0.04179699,  0.00231497],
        [-0.02009135,  0.02014704,  0.0042727 , -0.02297195,
         -0.01993846,  0.03533003,  0.00348381, -0.04113201,
          0.04179699,  0.00231497],
        [-0.02250183, -0.03241147,  0.02693602, -0.02282926,
          0.01453923,  0.04170242,  0.04764659,  0.0028908 ,
         -0.02710143, -0.04465578],
        [ 0.00543884,  0.03774575, -0.01967812, -0.00337263,
          0.03026557, -0.00735607,  0.02343133, -0.00289027,
         -0.0113731 ,  0.01741722],
        [-0.00125443, -0.03467407,  0.02348881,  0.0

In [33]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [34]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
onehot_repr

[[265, 396, 399, 241, 207, 103],
 [41, 364, 399, 442, 149, 377],
 [125, 61, 290, 444],
 [265, 282, 399, 107, 265, 439],
 [270, 237, 458, 399, 442, 149, 377],
 [5, 399, 442, 149, 134, 304]]

In [35]:
sent_length = 10
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[  0,   0,   0,   0, 265, 396, 399, 241, 207, 103],
       [  0,   0,   0,   0,  41, 364, 399, 442, 149, 377],
       [  0,   0,   0,   0,   0,   0, 125,  61, 290, 444],
       [  0,   0,   0,   0, 265, 282, 399, 107, 265, 439],
       [  0,   0,   0, 270, 237, 458, 399, 442, 149, 377],
       [  0,   0,   0,   0,   5, 399, 442, 149, 134, 304]], dtype=int32)

In [36]:
model = Sequential()
model.add(Embedding(voc_size , 20, input_length = sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


array([[[-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        [-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        [-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        ...,
        [ 0.04783464, -0.00247905, -0.0279742 , ..., -0.03479068,
         -0.04198575,  0.04823974],
        [-0.03007504, -0.00931122,  0.04206962, ...,  0.02670052,
          0.03296682,  0.04185667],
        [-0.03817235, -0.00187459, -0.01847782, ..., -0.0060653 ,
          0.00108498, -0.04615631]],

       [[-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        [-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        [-0.04204146, -0.00058816, -0.04306379, ...,  0.00820648,
         -0.02461942, -0.00349264],
        ...,
        [ 0.0362928 ,  0.03319501,  0.00136315, ..., -