In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
import pandas as pd
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [4]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
747/4825

0.15481865284974095

In [6]:
df_spam = df[df['Category']=='spam']
df_spam.shape

(747, 2)

In [7]:
df_ham = df[df['Category'] == 'ham']
df_ham.shape

(4825, 2)

In [8]:
df_ham_downsampled = df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 2)

In [9]:
df = pd.concat([df_spam, df_ham_downsampled])
df.shape


(1494, 2)

In [10]:
df['Category'].value_counts()

Category
spam    747
ham     747
Name: count, dtype: int64

In [11]:
df.sample(5)

Category                                            Message
4256     spam  Block Breaker now comes in deluxe format with ...
2226      ham  Alrite jod hows the revision goin? Keris bin d...
3671      ham                      Ok thanx... Take care then...
1466     spam  YOU 07801543489 are guaranteed the latests Nok...
5200     spam  Call Germany for only 1 pence per minute! Call...

In [12]:
import numpy as np
df['spam'] = np.where(df['Category'] == 'spam' ,1 , 0)

In [13]:
df.sample(10)

Category                                            Message  spam
3778     spam  Mila, age23, blonde, new in UK. I look sex wit...     1
3929      ham     Babe ? I lost you ... Will you try rebooting ?     0
3401     spam  As a valued customer, I am pleased to advise y...     1
2855      ham  Haha... Hope ü can hear the receipt sound... G...     0
3316     spam  FREE MESSAGE Activate your 500 FREE Text Messa...     1
2220     spam  You have WON a guaranteed £1000 cash or a £200...     1
4371     spam  Do you want a new Video handset? 750 any time ...     1
5409      ham            There is a first time for everything :)     0
459       ham  1.20 that call cost. Which i guess isnt bad. M...     0
1518     spam  Our brand new mobile music service is now live...     1

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Message'], df['spam'], stratify=df['spam'])

In [15]:
X_train.head()

2724    Tunde, how are you doing. This is just wishing...
2565    Under the sea, there lays a rock. In the rock,...
5387    I will be gentle baby! Soon you will be taking...
2583    3 FREE TAROT TEXTS! Find out about your love l...
1466    YOU 07801543489 are guaranteed the latests Nok...
Name: Message, dtype: object

In [61]:
!pip install -U "tensorflow-text==2.15.*"
!pip install -U "tf-models-official==2.15.*"


INFO: pip is looking at multiple versions of tf-keras to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 70.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 896.2 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 62.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 84.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 60.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 7.4 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.16.0
    Uninstalling wrapt-1.16.0:
      Successfully uninstalled wrapt-1.16.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 22.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.0/104.0 kB 10.6 MB/s eta 0:00:00
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16161 sha256=9011db10d12a541c228c4a0fb5dd93ee5ebd5aaadb0f4bfc816480ba0804fe10
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval


In [16]:

bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [17]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up",
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.843517  , -0.5132727 , -0.8884572 , ..., -0.7474886 ,
        -0.75314724,  0.91964495],
       [-0.8720834 , -0.50543964, -0.94446665, ..., -0.8584749 ,
        -0.7174534 ,  0.88082975]], dtype=float32)>

In [18]:

# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [19]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text (InputLayer)           [(None,)]                    0         []                            
                                                                                                  
 keras_layer (KerasLayer)    {'input_word_ids': (None,    0         ['text[0][0]']                
                             128),                                                                
                              'input_mask': (None, 128)                                           
                             , 'input_type_ids': (None,                                           
                              128)}                                                               
                                                                                              

In [20]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
model.fit(X_train , y_train , epochs = 20)

Epoch 1/20
35/35 [==============================] - 21s 335ms/step - loss: 0.5896 - accuracy: 0.7330
Epoch 2/20
35/35 [==============================] - 12s 345ms/step - loss: 0.4798 - accuracy: 0.8393
Epoch 3/20
35/35 [==============================] - 12s 338ms/step - loss: 0.4193 - accuracy: 0.8571
Epoch 4/20
35/35 [==============================] - 12s 334ms/step - loss: 0.3829 - accuracy: 0.8723
Epoch 5/20
35/35 [==============================] - 12s 340ms/step - loss: 0.3466 - accuracy: 0.8955
Epoch 6/20
35/35 [==============================] - 11s 318ms/step - loss: 0.3329 - accuracy: 0.8929
Epoch 7/20
35/35 [==============================] - 11s 326ms/step - loss: 0.3142 - accuracy: 0.8982
Epoch 8/20
35/35 [==============================] - 12s 331ms/step - loss: 0.3061 - accuracy: 0.9009
Epoch 9/20
35/35 [==============================] - 12s 335ms/step - loss: 0.2910 - accuracy: 0.9152
Epoch 10/20
35/35 [==============================] - 12s 334ms/step - loss: 0.2769 - accura

In [22]:
model.evaluate(X_test , y_test)

12/12 [==============================] - 5s 306ms/step - loss: 0.1831 - accuracy: 0.9385


[0.1830565333366394, 0.9385026693344116]

In [23]:
reviews = [
    'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service',
    'You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99',
    'it to 80488. Your 500 free text messages are valid until 31 December 2005.',
    'Hey Sam, Are you coming for a cricket game tomorrow',
    "Why don't you wait 'til at least wednesday to see if you get your ."
]
model.predict(reviews)

1/1 [==============================] - 1s 1s/step


array([[0.8985619 ],
       [0.9128899 ],
       [0.82218266],
       [0.15007146],
       [0.05164355]], dtype=float32)