In [1]:
import tensorflow_hub as hub
import tensorflow_text as text


In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [3]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [10]:
text_preprocessed['input_word_ids']
#cls nice movie indeed sep

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
bert_model = hub.KerasLayer(encoder_url)

In [12]:
bert_results =bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'pooled_output', 'default'])

In [14]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411909,  0.49769595, ...,  0.24465248,
        -0.47334474,  0.81758696],
       [-0.917123  , -0.4793516 , -0.7865695 , ..., -0.6175171 ,
        -0.71026856,  0.9218428 ]], dtype=float32)>

In [15]:
bert_results['sequence_output'] #individual word embedding vectors

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292055,  0.08567822,  0.14476837, ..., -0.09677067,
          0.08722132,  0.07711101],
        [ 0.1783942 , -0.1900609 ,  0.50349414, ..., -0.05869763,
          0.32717133, -0.15578507],
        [ 0.18701527, -0.43388727, -0.48875186, ..., -0.15502739,
          0.00145194, -0.24470969],
        ...,
        [ 0.12083019,  0.12884212,  0.46453553, ...,  0.07375549,
          0.17441961,  0.16522165],
        [ 0.07967892, -0.01190671,  0.50225407, ...,  0.13777724,
          0.21002257,  0.00624547],
        [-0.07212661, -0.28303477,  0.5903341 , ...,  0.47551954,
          0.1666847 , -0.08920329]],

       [[-0.0790057 ,  0.3633508 , -0.21101609, ..., -0.17183742,
          0.16299754,  0.6724269 ],
        [ 0.27883506,  0.43716297, -0.35764715, ..., -0.04463629,
          0.38315165,  0.5887988 ],
        [ 1.2037677 ,  1.0727019 ,  0.4840876 , ...,  0.24920993,
          0.4073093 ,  0.404818  ],
        ...,

In [21]:
bert_results['encoder_outputs']#output of encoders

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.1290142 ,  0.00644748, -0.03614981, ...,  0.04999622,
           0.06149191, -0.02657548],
         [ 1.1753383 ,  1.2140785 ,  1.1569979 , ...,  0.1163438 ,
          -0.3585539 , -0.40490198],
         [ 0.03859037,  0.53870016, -0.21089754, ...,  0.21858215,
           0.72601694, -1.1158608 ],
         ...,
         [-0.07587026, -0.25421932,  0.7075511 , ...,  0.50542015,
          -0.18878682,  0.15028363],
         [-0.160666  , -0.2808966 ,  0.5759706 , ...,  0.52758557,
          -0.11141399,  0.02887534],
         [-0.04428155, -0.20279576,  0.5909352 , ...,  0.8133835 ,
          -0.39075834, -0.02601742]],
 
        [[ 0.18903571,  0.02752544, -0.06513733, ..., -0.00620206,
           0.1505388 ,  0.03165448],
         [ 0.5916147 ,  0.758914  , -0.07240676, ...,  0.6190399 ,
           0.8292891 ,  0.16161981],
         [ 1.4460828 ,  0.44602662,  0.40990242, ...,  0.48255903,
           0.62691176,  0.13

In [19]:
bert_results['default']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411909,  0.49769595, ...,  0.24465248,
        -0.47334474,  0.81758696],
       [-0.917123  , -0.4793516 , -0.7865695 , ..., -0.6175171 ,
        -0.71026856,  0.9218428 ]], dtype=float32)>